build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank Loans related prod APIs"
  contactDetails:
    name: "Rachel ABISSY - Product Owner"
    email: "rachel.abissy@eazybank.com"
    onCallSupport:
      - (+228) 99534874
      - (+228) 97076132
