spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank Accounts related QA APIs"
  contactDetails:
    name: "Daniel YOSEF - QA Lead"
    email: "yosef@eazybank.com"
    onCallSupport:
      - (+228) 91554874
      - (+228) 99046133
